FROM alfg/nginx-rtmp

ENV ASM_NODE_ID="0"

ENV ASM_NGX_RMTP_WORKER_PROCESSES="auto"
ENV ASM_NGX_RMTP_WORKER_RLIMIT_NOFILE="81920"
ENV ASM_NGX_RMTP_ERROR_LOG_LEVEL="warn"
ENV ASM_NGX_RMTP_WORKER_CONNECTIONS="4096"
ENV ASM_NGX_RMTP_ACCESS_LOG_COMMENT="#"
ENV ASM_NGX_RMTP_PORT="1935"
ENV ASM_NGX_RMTP_SERVER_CHUNK_SIZE="2048"
ENV ASM_NGX_RMTP_SERVER_BUFLEN="10s"
ENV ASM_NGX_RMTP_SERVER_TIMEOUT="30s"
ENV ASM_NGX_RMTP_SERVER_DROP_IDLE_PUBLISHER="60s"
ENV ASM_NGX_RMTP_APP_LIVE_ON_PUBLISH="http://application-container:8080/live_auth_request"
ENV ASM_NGX_RMTP_APP_HLS_HLS_FRAGMENT="4"
ENV ASM_NGX_RMTP_APP_HLS_HLS_PLAYLIST_LENGTH="10"

ADD nginx/.defaults /defaults
ADD nginx/nginx.conf /etc/nginx/nginx.conf.template
