FROM alfg/nginx-rtmp

ENV ASM_NGX_RMTP_ACCESS_LOG_COMMENT="" \
  ASM_NGX_RMTP_WORKER_PROCESSES="auto" \
  ASM_NGX_RMTP_WORKER_RLIMIT_NOFILE="40960" \
  ASM_NGX_RMTP_WORKER_CONNECTIONS="2048" \
  ASM_NGX_RMTP_ERROR_LOG_LEVEL="warn" \
  ASM_NGX_RMTP_SERVER_CHUNK_SIZE="2048" \
  ASM_NGX_RMTP_SERVER_BUFLEN="10s" \
  ASM_NGX_RMTP_SERVER_TIMEOUT="30s" \
  ASM_NGX_RMTP_SERVER_DROP_IDLE_PUBLISHER="60s" \
  ASM_NGX_RMTP_APP_LIVE_ON_PUBLISH="http://application-container:8080/live_auth_request" \
  ASM_NGX_RMTP_APP_HLS_HLS_FRAGMENT="4" \
  ASM_NGX_RMTP_APP_HLS_HLS_PLAYLIST_LENGTH="10" \
  ASM_NGX_RMTP_CORS_DISABLE_COMMENT=""

ADD nginx/.defaults /defaults
ADD nginx/nginx.conf /etc/nginx/nginx.conf.template
